# Generated by Django 5.1.1 on 2024-09-14 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='status_recorrencia',
            field=models.DateField(verbose_name=''),
        ),
    ]
