# Generated by Django 5.1.1 on 2024-09-14 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamento', '0002_alter_pagamento_status_recorrencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='status_recorrencia',
            field=models.TextField(verbose_name=''),
        ),
    ]
