# Generated by Django 5.1.1 on 2024-09-14 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamento', '0004_pagamento_conta_pagamento_valor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
