# Generated by Django 5.1.1 on 2024-09-14 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamento', '0006_alter_pagamento_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
